### ISSUE TITLE
registration_agency takes wrong number of options

### ISSUE THREAD

**Issue by jronallo** [sckott/serrano#106]
When trying to use registration_agency I get the following error:

`ArgumentError: wrong number of arguments (given 14, expected 15)`

**Comment by sckott** [comment]
what version of `serrano` do you have?

**Comment by jronallo** [comment]
0.5.2

This error is raised with using the example from the readme.

**Comment by sckott** [comment]
thanks for the report, should be fixed now, can you test and let me know?

**Comment by jronallo** [comment]
Yes, this is fixed now. Thank you.
