### ISSUE TITLE
CLI tool 

### ISSUE THREAD

**Issue by sckott** [sckott/serrano#16]
using `thor` export a suite of cli tools

**Comment by sckott** [comment]
draft spec: 

```
~$ serrano
Commands:
  serrano works [String]         # Get metadata for a DOI, or a query term
  serrano help [COMMAND]  # Describe available commands or one specific command
```

**Comment by sckott** [comment]
@mfenner worked on cli tool, not on rubygems yet

example usage: 

```
$ serrano works 10.1371/journal.pone.0033693

  DOI: 10.1371/journal.pone.0033693
  type: journal-article
  title: Methylphenidate Exposure Induces Dopamine Neuron Loss and
  Activation of Microglia in the Basal Ganglia of Mice

$ serrano works 10.1007/12080.1874-1746 10.1007/10452.1573-5125

  DOI: 10.1007/12080.1874-1746
  type: journal
  title: Theoretical Ecology

  DOI: 10.1007/10452.1573-5125
  type: journal
  title: Aquatic Ecology

$ serrano works 10.1371/journal.pone.0033693 10.1007/12080.1874-1746 10.1007/10452.1573-5125 --json=true | jq .[].message.member

  "http://id.crossref.org/member/340"
  "http://id.crossref.org/member/297"
  "http://id.crossref.org/member/297"
```

**Comment by sckott** [comment]
And there's works as well, e.,g., 

```
$ serrano members 98 --works=true --json=true | jq .[].message.items[].\"reference-count\"

24 7 45 31 22 67 72 17 53 75 0 68 12 16 50 79 40 18 40 195
```

**Comment by sckott** [comment]
paging @gbilder - if you have any feedback on CLI tool at early stage esp. good

**Comment by mfenner** [comment]
Very cool. Do you want the output to be human-readable or machine-readable? How about Citeproc YAML - or is that what you are doing?

**Comment by sckott** [comment]
> Do you want the output to be human-readable or machine-readable?

Both. the `--json` flag is default `false` so you get brief summary of reach record. That brief summary could be anything, I just pulled a few fields, but it could be Citeproc YAML, though only when you are searching `/works` routes I imagine  - I was going for something brief, but perhaps not needed

**Comment by mfenner** [comment]
Cool. Maybe use YAML, which might not be Citeproc in some cases.

**Comment by sckott** [comment]
Okay. And the `--json=true` is to make it easy to pipe `|` outputs downstream, to e.g., `jq`. need to try to give back json directly though as now need to convert ruby hash back to json in the cli tool

**Comment by sckott** [comment]
to do: 

- [ ] Finish remainder of main routes: journals, funders, etc.
- [ ] what other top level commands? 
- [ ] give back citeproc yaml for brief output
- [ ] try to give back json directly instead of converting ruby hash back to json
- [ ] do we want to allow the various parameters in crossref api? query, filter, rows, etc.? if so, on same commands we have that accept IDs or diff. ones? if diff. that might be getting too busy

**Comment by sckott** [comment]
good for now, open new issues as needed
