### ISSUE TITLE
Return author when using Serrano.works(query: "<query">)

### ISSUE THREAD

**Issue by pilmus** [sckott/serrano#39]
Currently, the author is not available in the information returned by `Serrano.works(query: "<query>")`. Would be very useful!

**Comment by sckott** [comment]
thx for the issue @pilmus 

having a look

**Comment by sckott** [comment]
I'm pretty sure `author` is always returned, but if you can point to egs where it's not that'd be useful

try this eg. 

```ruby
require 'serrano'
res = Serrano.works(query: "ecology")
res['message']['items'].collect { |x| x['author'] }
```
