### ISSUE TITLE
>= ruby 2.4.0 warns that constant ::Fixnum is deprecated

### ISSUE THREAD

**Issue by dshorthouse** [sckott/serrano#50]
https://github.com/sckott/serrano/blob/e778042b373d16e6afd1e50e9867e5744574fed9/lib/serrano/request_cursor.rb#L65

Could this instead be:

```ruby
if !self.cursor_max.kind_of?(Integer)
  raise "cursor_max must be of class int"
end
```

**Comment by sckott** [comment]
thanks @dshorthouse will have a look
