### ISSUE TITLE
Fails to handle DOIs with unusual characters

### ISSUE THREAD

**Issue by smackesey** [sckott/serrano#51]
This fails:

    Serrano.works(ids: '10.1002/1096-9861(20010212)430:3<283::aid-cne1031>3.0.co;2-v')

But this works:

    encoded_doi = ERB::Util.url_encode('10.1002/1096-9861(20010212)430:3<283::aid-cne1031>3.0.co;2-v')
    Serrano.works(ids: encoded_doi)

Serrano should probably perform this URL encoding for the user.

**Comment by sckott** [comment]
Thanks for this @smackesey 

I agree we should probably do the url encoding

**Comment by sckott** [comment]
@smackesey can you reinstall from github and try again ?
