### ISSUE TITLE
Does this affect Serrano?

### ISSUE THREAD

**Issue by arfon** [sckott/serrano#69]
:wave: @sckott - I just received [this email](http://outreach.crossref.org/acton/rif/16781/s-01c4-1904/-/l-0205:751/l-0205/showPreparedMessage?utm_term=View%20this%20message%20in%20your%20browser&utm_campaign=Simple%20Text%20Query%20for%20matching%20references%20is%20being%20replaced&utm_content=email&utm_source=Act-On+Software&utm_medium=email&cm_mmc=Act-On%20Software-_-email-_-Simple%20Text%20Query%20for%20matching%20references%20is%20being%20replaced-_-View%20this%20message%20in%20your%20browser&sid=TV2:pueq97ip7) from Crossref support stating that the ` Simple Text Query` is being replaced at the end of April. 

Do you know if this affects Serrano, in particular the `Serrano.works` queries?

**Comment by sckott** [comment]
thanks @arfon for the ping. I'll investigate and get back

**Comment by sckott** [comment]
https://github.com/CrossRef/rest-api-doc/issues/452#issuecomment-480423578 sounds like they are keeping that service a bit longer, and doesn't affect the API at least right now

**Comment by arfon** [comment]
👍 thanks for checking in on this @sckott
