### ISSUE TITLE
Response class?

### ISSUE THREAD

**Issue by sckott** [sckott/serrano#8]
Make a new response class to hold results?  Or stick with `Faraday::Response` object?  Benefits of a new class is full control, but sticking with the `Faraday::Response` builds on all the hard work done already on that gem

**Comment by sckott** [comment]
@mfenner What is best practice in Ruby with respect to this question? From your point of view, would you rather get back the raw `Faraday::Response` object or something else?  If  not the `Faraday::Response` object, seems a new response class defined in this client would be best, with methods on the response class for parsing, response status, etc.

**Comment by mfenner** [comment]
See my utility class here: https://github.com/lagotto/lagotto/blob/master/app/models/concerns/networkable.rb. The tricky bit is error handling, as you want to catch them and give a meaningful message back to the user. I use response.body and parse the JSON (or XML) if there is no error.

**Comment by mfenner** [comment]
In other words, if there is no error you probably are only interested in response.body.

**Comment by mfenner** [comment]
My utility class for DOIs is here: https://github.com/lagotto/lagotto/blob/master/app/models/concerns/resolvable.rb

**Comment by sckott** [comment]
Thanks. Right, that is a lot of work for error handling

**Comment by mfenner** [comment]
You can probably get away with less. But I collected this over time. A simpler version is at https://github.com/crosscite/doi-metadata-search/blob/master/lib/network.rb

**Comment by sckott** [comment]
Given cursor for paging in the API #14 I think it makes sense to have a class for the response object so that we can maintain state, esp since this cursor approach to paging is esp not very easy for a user to handle manually

**Comment by sckott** [comment]
Would still be nice to return a hash by default if no errors since users can easily process that as needed

**Comment by mfenner** [comment]
yes, I like hash as standard response, with an `:error` attribute if an error occured. Thinking about JSON API, maybe the standard key for a positive response could be `:data`.

**Comment by sckott** [comment]
data is a good idea, haven't had to do that so far as no internal paing, but once that's used, will need to do that when combining results

**Comment by mfenner** [comment]
haven't thought much about it, but would be interesting to see how much you can propagate API conventions into the processing of the response.

**Comment by sckott** [comment]
Good idea. will think about that

**Comment by sckott** [comment]
will need to create a class for maintaining state for using cursor, see #14 , but can still just return hash/array

**Comment by sckott** [comment]
closing for now, returning hash/array
